### ISSUE TITLE
Trying to verify a memory returns `422 Unprocessable entity`

### ISSUE THREAD

**Issue by villenattinen** [MuistotKartalla/muistot-backend#34]
Verifying a memory seems to be broken:

![Image](https://github.com/MuistotKartalla/muistot-backend/assets/71127121/5e99db38-c825-402b-9f5f-8a67112fb113)

- [ ] Investigate if the issue is in frontend or backend (if the issue is in frontend, transfer this issue to that repo)

**Comment by Dilafdo** [comment]
This happens because of this issue. https://github.com/MuistotKartalla/muistot-backend/issues/24

**Comment by villenattinen** [comment]
Oops, I'll remove this as duplicate.
